### ISSUE TITLE
ServiceHolder static references are not getting populated

### ISSUE THREAD

**Issue by msm1992** [wso2-extensions/apim-migration-resources#190]
**Description:**

ex:
```
public static void setOrganizationResolver(OrganizationResolver organizationResolver) {
        organizationResolver = organizationResolver;
}
```

Above should be modified into,

```
public static void setOrganizationResolver(OrganizationResolver organizationResolver) {
        ServiceHolder.organizationResolver = organizationResolver;
}
```

Methods to be fixed,
* setOrganizationResolver
* setArtifactSaver
* setImportExportAPI

**Related Issues:**

- [x] https://github.com/wso2-extensions/apim-migration-resources/issues/191

**Comment by dushaniw** [comment]
fixed with https://github.com/wso2-extensions/apim-migration-resources/pull/192
