### ISSUE TITLE
Missing some important data population flows in apim-data-populator 

### ISSUE THREAD

**Issue by HiranyaKavishani** [wso2-extensions/apim-migration-resources#233]
**Description:**
Following data has to be populated from apim-data-populator script

Updated: 2022.08.09

- [ ] API-M 2.6.0, API-M-3.0.0, API-M 3.1.0 scripts : Infinite tokens with opaque and JWT token type apps
- [ ] API-M-400 Adding new GW environment
- [ ] Create SOAP API with WSDL archive
- [ ] Add endpoint security to API

**Comment by msm1992** [comment]
More scenarios to add,
1. Create SOAP API with WSDL archive
2. Add endpoint security to API

**Comment by dushaniw** [comment]
tracked with https://github.com/wso2/api-manager/issues/599
