### ISSUE TITLE
Not able to see published APIs after migrating from 2.6.0 to 3.1.0

### ISSUE THREAD

**Issue by prasad4491** [wso2-extensions/apim-migration-resources#25]
[audit.log](https://github.com/wso2-extensions/apim-migration-resources/files/4895329/audit.log)
[wso2-apigw-errors.log](https://github.com/wso2-extensions/apim-migration-resources/files/4895330/wso2-apigw-errors.log)
[wso2-apigw-service.log](https://github.com/wso2-extensions/apim-migration-resources/files/4895331/wso2-apigw-service.log)
[wso2carbon.log](https://github.com/wso2-extensions/apim-migration-resources/files/4895334/wso2carbon.log)

**Description:**
Not able to see published APIs after migrating from 2.6.0 to 3.1.0

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
WSO 2 APIM 3.1.0
**OS, DB, other environment details and versions:**    
OS : Windows 10
DB: Postgres 9.6
Previous APIM Version 2.6.0
Migrated APIM Version 3.1.0
**Steps to reproduce:**
I just followed the steps in the below link.
[https://apim.docs.wso2.com/en/latest/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-310/#step-2-upgrade-api-manager-to-310
](https://apim.docs.wso2.com/en/latest/install-and-setup/upgrading-wso2-api-manager/upgrading-from-260-to-310/#step-2-upgrade-api-manager-to-310
)

But If I don't remove solr directory as mentioned in the below steps then I can see published APIS in Publisher and devportal
Step 2 - Upgrade API Manager to 3.1.0
  7. Re-index the artifacts in the registry.
     d. If the <API-M_3.1.0_HOME>/solr directory exists, take a backup and thereafter delete it.
**Related Issues:**

**Comment by dushaniw** [comment]
@prasad4491 it seems to be a reindexing issue. Did you add the following to deployment.toml after deleting solr directory and before starting the server?

`[indexing]
re_indexing= 1
`

**Comment by dushaniw** [comment]
Closing as no recent update.
